### ISSUE TITLE
macOS X EI Captain 10.11.6 上 GoLand 2021.3.3 下载和编译都报错 dyld: Symbol not found: _clock_gettime

### ISSUE THREAD

**Issue by TommyLemon** [keepfoo/apijson-go#11]
这是 Go 与 macOS 兼容问题导致，能支持比 1.16 更低的 Go 版本吗？
https://github.com/pocoproject/poco/issues/1453
https://stackoverflow.com/questions/39544703/getting-error-dyld-symbol-not-found-clock-gettime

![image](https://user-images.githubusercontent.com/5738175/162991716-29f8edd1-4172-4fe5-adff-2f7cd5b7c8f2.png)

![image](https://user-images.githubusercontent.com/5738175/162992390-ceab0c53-59bd-499e-bbdd-e70ff76556b6.png)

Windows 10 上最新版 GoLand 可以正常编译和运行，用 test.http 内的示例测试功能正常。
改了代码后也支持 APIAuto 直接测试
![image](https://user-images.githubusercontent.com/5738175/162992958-51563daf-e4e1-436e-bda6-3e62fca2b565.png)

**Comment by TommyLemon** [comment]
github.com/go-sql-driver/mysql v1.6.0 要求 Go 最低 1.3，
github.com/jmoiron/sqlx  v1.3.1 未找到最低要求，
github.com/lib/pq v1.3.0 未找到最低要求。

本地注释这 3 个库的代码后，使用 Go 1.13.15 可以正常编译运行（除了连数据库增删改查）

**Comment by j2go** [comment]
我用 ubuntu 的 go 1.13.8 编译没有问题
![2022-04-21 02-16-23 的屏幕截图](https://user-images.githubusercontent.com/9101755/164296424-80fb9980-b681-422f-ada4-3ddc05086db3.png)
