### ISSUE TITLE
运行有问题

### ISSUE THREAD

**Issue by bigdaronlee163** [keepfoo/apijson-go#16]
为什么运行之后，
![image](https://user-images.githubusercontent.com/49524138/167395906-ddb2a73d-39b8-4a47-b57b-db359a77c836.png)

然后在测试接口，返回结果报表不存在的错误。

![image](https://user-images.githubusercontent.com/49524138/167396160-a9a87163-f038-4802-81f8-3d15aa1d1993.png)

数据库已经导入了。

![image](https://user-images.githubusercontent.com/49524138/167396419-4db21851-375a-4bfa-817a-28ae1cfd4ab9.png)

数据库的版本是8.xxx的

**Comment by TommyLemon** [comment]
需要把 "Document" 改为全小写 "document"，它在启动时加载了所有表名和字段名，Windows 上 MySQL 数据库表名、字段名都默认是小写。
@j2go 这个建议优化下，把加载到内存 map 的表名 name 首字母都大写~
https://github.com/j2go/apijson-go/blob/main/db/db.go#L53

@bigdaronlee163 你也可以改下，提个 Pull Request 给作者合并

**Comment by j2go** [comment]
或者全部转成小写

**Comment by bigdaronlee163** [comment]
好的，最近可以提交一个PR，可以将这个issue分给我，最近搞别的东西，忘记看了

**Comment by bigdaronlee163** [comment]
@j2go

**Comment by j2go** [comment]
fixed
